config:
    - !!models.Config
        name: "is.prod"
        content: "no"
        typeEnum: 3
        comment: "是否生产模式(yes/no)"

    - !!models.Config
        name: "admin.login"
        content: "yes"
        typeEnum: 3
        comment: "是否启用管理员权限(yes/no), 若不启用则后台不需要管理员登陆"

    - !!models.Config
        name: "websocket"
        content: "no"
        typeEnum: 3
        comment: "是否启用即时通讯"

    - !!models.Config
        name: "app.name"
        content: "租金所"
        typeEnum: 0
        comment: "网站名称"

    - !!models.Config
        name: "sms.server"
        content: "sms.todaynic.com"
        typeEnum: 0
        comment: "第三方短信验证码服务器"

    - !!models.Config
        name: "sms.port"
        content: "20002"
        typeEnum: 0
        comment: "第三方短信验证码端口"

    - !!models.Config
        name: "sms.uid"
        content: "ms1614"
        typeEnum: 0
        comment: "第三方短信验证码用户名"

    - !!models.Config
        name: "sms.psw"
        content: "mtod"
        typeEnum: 0
        comment: "第三方短信验证码密码"

    - !!models.Config
        name: "weixin.appid"
        content: "wx72a592fac58f16"
        typeEnum: 0
        comment: "微信公众号appid"

    - !!models.Config
        name: "weixin.secret"
        content: "c4769db99d42940c18bb63e498652e"
        typeEnum: 0
        comment: "微信公众号secret"

    - !!models.Config
        name: "weixin.token"
        content: "fangdgle"
        typeEnum: 0
        comment: "微信公众号token"

    - !!models.Config
        name: "weixin.aes"
        content: "YgVEG3AfIcq0ydGB5zgAtSwpF6XWZ7eaQhV1FXmz8"
        typeEnum: 0
        comment: "微信公众号aes"

    - !!models.Config
        name: "protocol"
        content: "http"
        typeEnum: 0
        comment: "协议(http或https)"

    - !!models.Config
        name: "domain.name"
        content: "fangdl.woyik.com"
        typeEnum: 0
        comment: "域名 (若本地则localhost:9000, 带端口号), 不带http头"

    - !!models.Config
        name: "company.name"
        content: "珠海横琴金融服务有限公司"
        typeEnum: 0
        comment: "公司名称"

    - !!models.Config
        name: "user.timeout.minute"
        content: "30"
        typeEnum: 1
        comment: "用户登陆过期时间(分钟), 超过此时间需重新登陆"

    - !!models.Config
        name: "admin.timeout.minute"
        content: "30"
        typeEnum: 1
        comment: "管理员登陆过期时间(分钟), 超过此时间需重新登陆"

    - !!models.Config
        name: "forget.password.email.timeout.minute"
        content: "30"
        typeEnum: 1
        comment: "重置密码邮件验证的过期时间(分钟), 超过此时间需要重新申请"

    - !!models.Config
        name: "email.send.protect.second"
        content: "20"
        typeEnum: 1
        comment: "邮件发送频率保护时间(秒)"

    - !!models.Config
        name: "dbbak.receive.email"
        content: "db_bak@126.com"
        typeEnum: 0
        comment: "接收数据库备份文件的邮箱地址"

    - !!models.Config
        name: "smtp.host"
        content: "smtp.126.com"
        typeEnum: 0
        comment: "发件邮箱SMTP地址, 如smtp.126.com"

    - !!models.Config
        name: "smtp.user"
        content: "db_bak@126.com"
        typeEnum: 0
        comment: "发件邮箱用户名"

    - !!models.Config
        name: "smtp.password"
        content: "emuml7080"
        typeEnum: 0
        comment: "发件邮箱密码"

    - !!models.Config
        name: "pic.thumb.size"
        content: "200"
        typeEnum: 2
        comment: "图片缩略图尺寸(如200)"

    - !!models.Config
        name: "pic.mid.thumb.size"
        content: "500"
        typeEnum: 2
        comment: "图片中等缩略图尺寸(如500)"